main:
	@echo "Compilando ficheros..."
	g++ -std=c++20 src/main.cc src/laberinto/laberinto.cc -o busqueda_informada

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f busqueda_informada