main:
	@echo "Compilando ficheros..."
	g++ -std=c++20 src/main.cc src/nodo/nodo.cc src/arbol/arbol.cc -o busqueda_no_informada

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f busqueda_no_informada